### ISSUE TITLE
Add in-line keyboard to various commands.

### ISSUE THREAD

**Issue by DoDi1408** [DoDi1408/javabot-telegram#4]
As @elunac19 showed us, ux improves when using buttons compared to typing the commands. 
Commands that should have this feature should be: 

-/joinTeam: join team should display in-line the various team options the user can join.
- /todoList: We should add in-line keyboards to display extensive information about a task. 
- OR /todoList should become a carrousel of sorts. Where we show information about 1 task, and we can cycle forward (i.e. show the next task) or cycle backwards (showing the previous task) If we do this. We should add one more inline button to EDIT this task.
Its hard to explain in an issue, we should discuss this in person with a whiteboard preferably.

**Comment by elunac19** [comment]
Resolved: Implemented inline keyboards for enhanced user experience in the ToDoList functionality. Divided the functionality into three parts: Task Options, StateTask, and GetTask, each providing users with specific actions and detailed task information. Additionally, integrated inline keyboards for commands /joinTeam
